[workspace]
members = [
    "rs/hang",
    "rs/hang-cli",
    "rs/libmoq",
    "rs/moq-clock",
    "rs/moq-lite",
    "rs/moq-native",
    "rs/moq-relay",
    "rs/moq-token",
    "rs/moq-token-cli",
]
resolver = "2"

[workspace.dependencies]
hang = { version = "0.9", path = "rs/hang" }
moq-lite = { version = "0.10", path = "rs/moq-lite" }
moq-native = { version = "0.10", path = "rs/moq-native" }
moq-token = { version = "0.5", path = "rs/moq-token" }

serde = { version = "1", features = ["derive"] }
tokio = "1.48"
web-async = { version = "0.1.1", features = [
	"tracing",
], path = "../web-rs/web-async" }
web-transport-quinn = { version = "0.10", path = "../web-transport/web-transport-quinn" }
web-transport-trait = { version = "0.3", path = "../web-transport/web-transport-trait" }
web-transport-ws = { version = "0.2", path = "../web-transport/web-transport-ws" }
